### ISSUE TITLE
Defect report

### ISSUE THREAD

**Issue by anedejour** [kazet/wpgarlic#5]
Does the tool have a defect report?

**Comment by kazet** [comment]
I'm afraid I don't understand the question.

**Comment by DanielRuf** [comment]
Defect reports are more detailed written reports with summaries and so on (like in pentest reports, bug reports and so on).

https://duckduckgo.com/?t=ffab&q=defect+report&ia=web

I guess some sort of markdown or txt reporter is meant.

**Comment by kazet** [comment]
The only type of output is the raw fuzzer output described in the README, e.g.: https://github.com/kazet/wpgarlic/raw/main/examples/responsive-vector-maps.png

Unfortunately, converting it to a bug report that can be submitted e.g. to the vendor requires manual work (including interpreting, whether the report is a true or a false positive).
