### ISSUE TITLE
Failing to fuzz folder containing plugins

### ISSUE THREAD

**Issue by 0Ky** [kazet/wpgarlic#7]
I'm unable to fuzz multiple plugins located in a folder using the `--file-or-folder-to-fuzz` option, when I've tried directly running `./bin/fuzz_plugin <folder path>`, this led to an error:
```
Traceback (most recent call last):
  File "/home/user/wpgarlic/fuzz_plugin.py", line 234, in <module>
    typer.run(fuzz_plugin)
  File "/home/user/wpgarlic/fuzz_plugin.py", line 69, in fuzz_plugin
    assert all(
AssertionError
```
Any guidance or a potential fix would be appreciated.

Running on Ubuntu 22.04.3 LTS on WSL2.

**Comment by kazet** [comment]
Hello,

`--file-or-folder-to-fuzz` describes what plugin files or folders to fuzz inside the container (for example to detect what would happen if the user would visit a .php file directly with some interesting GET or POST parameters). You most probably don't want to use this, as by default all php files are checked.

To fuzz multiple plugins located in a folder, fuzz each of them one-by-one - `./bin/fuzz_plugin` supports fuzzing a single plugin zip file.
